<table class="form-table">
	<tbody>
	<tr>
		<th scope="row"><label for="post_title"><? _e('Title', OSC) ?></label></th>
		<td>
			<input type="text" style="width: 100%" value="<?= esc_attr($post->post_title) ?>"
			       placeholder="<? esc_attr(_e('Title', OSC)) ?>"
			       name="post_title" id="post_title" required="required"/>
		</td>
	</tr>

	<tr>
		<th></th>
		<td>
			<? wp_editor(
				$post->post_content, 'content', [
					'dfw' => false,
					'teeny' => true,
					'wpautop' => false,
					'quicktags' => false,
					'drag_drop_upload' => false,
					'media_buttons' => false,
					'editor_height' => 600,
					'textarea_name' => 'content',
					'editor_class' => 'large-text'
				]
			); ?>
		</td>
	</tr>
	</tbody>
</table>

<? wp_nonce_field('send-news-nonce', 'send-news-nonce') ?>